theme: minima
title: Fane all the things
author: Gaijin
email: notmyemail.com
description: > # this means to ignore newlines until "baseurl:"
  test the feed search. special words ets

# social links
twitter_username: cindling # DO NOT include the @ character, or else the build will fail!
github_username:  bokuwagaijin # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
